name: Check Style
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install packages
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Run ESLint
        run: yarn run lint
